apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: default
data:
  index.html: |
    <html>
    <div align="center">
    <h1>Welcome</h1>
    </br>
    <h1>Hi! This is a custom Index file for LuxCampus homework</h1>
    </div>
    </html>
